### ISSUE TITLE
Running in VMWARE

### ISSUE THREAD

**Issue by xxxkrogoth** [Infosys/openIDP#27]
Ubuntu 16.04 image running in VMWARE
12GB allocated
150 GB HD space

Checking Config Server failed at end of build.sh

I have tried all the bug issues already covered here as of 1-6-2019, including setting the build.sh to only do the healthcheck. Really need help getting this going in a VM for a POC.

**Comment by manishbansal8843** [comment]
When you say "config server failed", you mean during health check? If that is the case, please ignore it as for me also, health check never passed. If no, please share the config server logs.

**Comment by xxxkrogoth** [comment]
Thank you for the quick help. I am running it in a VM on a machine with only 16 GB total memory, but next week I am going to try it on a standalone with 32 GB of memory. I cant push the VM much more past 12GB for now.

**Comment by xxxkrogoth** [comment]
Thanks! I will give it a shot today. I already modified the original build.sh to allow more time to run the health check, but lets see if this helps. Also, 3 types of Linux types are mentioned in the beginning. CentOS 7, Ubuntu 16.x and RHEL 7.x. Any particular distribution work better than others?

**Comment by xxxkrogoth** [comment]
idp/idpdeployment:latest is not running when I do Docker service list. Any ideas how to manually start this? I am really close on this.

**Comment by jaskirat8** [comment]
@xxxkrogoth That component "idpdeployment" is in beta testing hence not released. I understand your confusion from pictures in Wiki page. You can ignore that. We will fix those images.

Your cluster seems to be running correctly. Are you able to hit the url ?

**Comment by xxxkrogoth** [comment]
No I cannot get into the IDP website on 8080. I can get into Keycloak and base Apache Tomcat pages and do the written modifications for Keycloak:8989
. Here is the port report-

Not shown: 65524 closed ports
PORT      STATE SERVICE
2181/tcp  open  unknown
2377/tcp  open  unknown
3000/tcp  open  ppp
5432/tcp  open  postgresql
7946/tcp  open  unknown
8085/tcp  open  unknown
8761/tcp  open  unknown
8888/tcp  open  sun-answerbook
8989/tcp  open  unknown
9092/tcp  open  unknown
50000/tcp open  ibm-db2



I also see a lot of things saying it needs to load manually. Here is the load log.


Compiling UI .......
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN ang-jsoneditor@1.7.1 requires a peer of @angular/core@>=6.0.0-rc.5 but none is installed. You must install peer dependencies yourself.
npm WARN ang-jsoneditor@1.7.1 requires a peer of @angular/common@>=6.0.0-rc.5 but none is installed. You must install peer dependencies yourself.
npm WARN angular-2-data-table@0.1.2 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-table@1.3.2 requires a peer of @angular/common@~2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-table@1.3.2 requires a peer of @angular/compiler@~2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-table@1.3.2 requires a peer of @angular/core@~2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-table@1.3.2 requires a peer of @angular/forms@~2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-translate@5.0.0 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-translate@5.0.0 requires a peer of @angular/http@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-treeview@6.0.2 requires a peer of @angular/common@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-treeview@6.0.2 requires a peer of @angular/core@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-treeview@6.0.2 requires a peer of @angular/forms@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


Your global Angular CLI version (6.2.1) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

**Comment by xxxkrogoth** [comment]
docker service inspect IDP_oauth

[
    {
        "ID": "1pvxnf1ladu0cavdyujjhc46y",
        "Version": {
            "Index": 429
        },
        "CreatedAt": "2019-01-08T15:38:34.496573446Z",
        "UpdatedAt": "2019-01-08T15:38:34.498652433Z",
        "Spec": {
            "Name": "IDP_oauth",
            "Labels": {
                "com.docker.stack.image": "idp/idpoauth",
                "com.docker.stack.namespace": "IDP"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "idp/idpoauth:latest",
                    "Labels": {
                        "com.docker.stack.namespace": "IDP"
                    },
                    "Env": [
                        "CONFIG_HOSTNAME=ubuntu",
                        "CONFIG_PASSWORD=idpadmin@123",
                        "CONFIG_PORT=8888",
                        "CONFIG_USERNAME=idpadmin",
                        "DASHBOARD_HOSTNAME=ubuntu",
                        "DASHBOARD_PORT=8184",
                        "EUREKA_HOSTNAME=ubuntu",
                        "EUREKA_PORT=8761",
                        "GRAFANA_HOSTNAME=ubuntu",
                        "GRAFANA_PORT=3000",
                        "IDPAPP_HOSTNAME=ubuntu",
                        "IDPAPP_PORT=8080",
                        "JENKINS_HOSTNAME=ubuntu",
                        "JENKINS_PASSWORD=650f0ef465ef16b5a8e1bdcbd461973c",
                        "JENKINS_PORT=8085",
                        "JENKINS_USERNAME=idpadmin",
                        "KAFKA_HOSTNAME=kafka",
                        "KAFKA_PORT=9092",
                        "KEYCLOAK_HOSTNAME=ubuntu",
                        "KEYCLOAK_PASSWORD=admin",
                        "KEYCLOAK_PORT=8989",
                        "KEYCLOAK_USER=admin",
                        "OAUTH_HOSTNAME=ubuntu",
                        "OAUTH_PORT=8181",
                        "POSTGRES_DEFAULT=keycloak",
                        "POSTGRES_HOSTNAME=postgres",
                        "POSTGRES_PASSWORD=root",
                        "POSTGRES_PORT=5432",
                        "POSTGRES_USER=postgres",
                        "PROFILE=paas",
                        "SCHEDULER_HOSTNAME=ubuntu",
                        "SCHEDULER_PORT=8222",
                        "SERVICES_HOSTNAME=ubuntu",
                        "SERVICES_PORT=8889",
                        "SSL_ENABLED=false",
                        "SUBSCRIPTION_HOSTNAME=ubuntu",
                        "SUBSCRIPTION_PORT=8090",
                        "TZ=Asia/Kolkata",
                        "ZOOKEEPER_HOSTNAME=zookeeper",
                        "ZOOKEEPER_PORT=2181"
                    ],
                    "Privileges": {
                        "CredentialSpec": null,
                        "SELinuxContext": null
                    },
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {},
                "Networks": [
                    {
                        "Target": "6oan3ihrta9od8ya1ute1srul",
                        "Aliases": [
                            "oauth"
                        ]
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 8181,
                        "PublishedPort": 8181,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 8181,
                        "PublishedPort": 8181,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 8181,
                    "PublishedPort": 8181,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "bnulpjbi989xm2gov5rvrgma3",
                    "Addr": "10.255.0.73/16"
                },
                {
                    "NetworkID": "6oan3ihrta9od8ya1ute1srul",
                    "Addr": "10.0.2.23/24"
                }
            ]
        }
    }
]






**docker logs -f $(docker ps | grep oauth | awk '{ print $1 }')**


root@ubuntu:~/openIDP# docker logs -f $(docker ps | grep oauth | awk '{ print $1 }')
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....
Waiting for Config Server to start. Sleeping for 5 sec .....

**Comment by jaskirat8** [comment]
@xxxkrogoth Its clear from the logs that the hostname i.e. "ubuntu" of your VM is not getting resolved in containers. Hence handshake not occuring. 
Network setup is not working. Suggest you to either fix hostname resolution for VM or use the machine IP for setup by giving that value to HOSTNAME variable in script as mentioned [here](https://github.com/Infosys/openIDP/wiki/Installation).

In both case, please ensure you have required ports forwarded from VM to host OS via bridge setup or use NAT for direct access, unless you are planing to run X-server/GNOME session in your ubuntu installation in that case you can use the browser of ubuntu installation itself to check since port will be local in that case.

**Comment by xxxkrogoth** [comment]
Should I use a FQDN for it in the script after I set up the hostname on the unit. Like test.ubuntu.server for instance? Also, for now I am using it locally with  a minimal LXDE and Firefox and still cannot get to it in the VM Nat. Once I can get into it with the NAT in the VM I will test if I can get to it outside the virtual setup.

**Comment by xxxkrogoth** [comment]
Also, is their a way to uninstall openIDP completely, or disable it?

**Comment by jaskirat8** [comment]
@xxxkrogoth  Yes you can use FQDN but bear in mind in that case its accessible only within your unit unless you replicate the DNS setup. 

So as per your statement this is what i understood, that you have setup IDP in a VM and trying to access it from VM only. Correct me if i am wrong.
Because in that case all you need to do is replace hostname variable in build script with 127.0.0.1 or ip address of your virtual ethernet port setup in VM which can be found by 

> ifconfig -a

Also for uninstalling IDP, its simple 2 steps.

1. Fire the following command to remove the docker stack
`docker stack rm IDP`

2. Delete the openIDP folder

and its clean, no trace of IDP on your system.

**Comment by xxxkrogoth** [comment]
Yes, trying to connect to it only inside the VM. Did the local host IP, didn't work. Did the Hostname -I (IP) and that didn't work as well. updated hosts file and did all the other stuff to try and  get it going and still cannot get to it from the browser.

**Comment by xxxkrogoth** [comment]
Jaskirit, can you try and duplicate this on VMWare workstation? It would be beneficial to have this able to run in a VM environment.

**Comment by xxxkrogoth** [comment]
Can anyone try and get this to run in a VM like VMWARE WORKSTATION?

**Comment by jaskirat8** [comment]
We will try to give it a shot. Please share the network configuration you used for your VM plus what was the Host OS ?

**Comment by xxxkrogoth** [comment]
The network configuration is standard NAT and the OS was CentOS

**Comment by xxxkrogoth** [comment]
jaskirat8, any updates on this?
